name: skypt_app
description: Seu projeto Skypt
publish_to: 'none' # Remove isto se for publicar
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.2
  path_provider: ^2.1.5
  path: ^1.9.1
  crypto: ^3.0.6
  provider: ^6.0.0
  google_fonts: ^6.1.0
  flutter_speed_dial: ^7.0.0
  fl_chart: ^0.66.2
  window_manager: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/intro.png